### ISSUE TITLE
Check latest versions of the BOINC server against what we run in LHC@Home

### ISSUE THREAD

**Issue by rdemaria** [SixTrack/BoincIssues#15]

**Comment by ericmcintosh** [comment]
The received_date in the result database directory should be initialised
to null not 0. There are probably other fields to which this remark should apply.
Don't know if this is done by BOINC or what....

**Comment by rdemaria** [comment]
It is deep in the C code of BOINC see:

https://github.com/BOINC/boinc/blob/381e0caf1489b5d1190563e96ce95f64bc385265/tools/backend_lib.cpp#L83

and

https://github.com/BOINC/boinc/blob/master/db/boinc_db.h#L185

**Comment by ericmcintosh** [comment]
Great work Riccardo, so now we need to know if it has been changed in later versions.
I don't think the server has been updated...but i don't know. For IT/Igor I guess.   Eric.
________________________________

**Comment by rdemaria** [comment]
The server software is recent (github master november 2016). It will be updated when redeployed. The software does not have a strict release policy.
